### ISSUE TITLE
Extract a method that parses soup object and extracts information from it.

### ISSUE THREAD

**Issue by aidiss** [yomajo/Weekly-Investment-Report#11]

**Comment by yomajo** [comment]
Consider it done with this commit:
https://github.com/yomajo/Weekly-Investment-Report/commit/37a845803b5e24b0b508788a611dc64a64d23ea6

**Comment by aidiss** [comment]
@yomajo nice :)

**Comment by yomajo** [comment]
Thanks @aidiss . :) Told you, I would be back to this project. Will tag, whenever I'l' feel like it's about done.
